-- Create a new schema for dbt models
-- You can change 'DBT_MODELS' to any name you prefer
CREATE SCHEMA IF NOT EXISTS DQLABS_QA.DBT_MODELS;

-- Grant necessary permissions to your role
GRANT USAGE ON SCHEMA DQLABS_QA.DBT_MODELS TO ROLE PUBLIC;
GRANT CREATE TABLE ON SCHEMA DQLABS_QA.DBT_MODELS TO ROLE PUBLIC;
GRANT CREATE VIEW ON SCHEMA DQLABS_QA.DBT_MODELS TO ROLE PUBLIC;

-- Verify the schema was created
SHOW SCHEMAS IN DATABASE DQLABS_QA; 