-- Alter the existing retail_sales table to add missing columns
-- This preserves existing data while adding the RECORD_ID column

-- Step 1: Add RECORD_ID column if it doesn't exist
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS RECORD_ID VARCHAR(50);

-- Step 2: Update RECORD_ID with sequential values for existing records
UPDATE DQLABS_QA.STAGING.RETAIL_SALES 
SET RECORD_ID = ROW_NUMBER() OVER (ORDER BY "DATE", STORE_ID, PRODUCT_NAME)
WHERE RECORD_ID IS NULL;

-- Step 3: Check if DATE column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS "DATE" DATE;

-- Step 4: Check if STORE_ID column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS STORE_ID VARCHAR(20);

-- Step 5: Check if PRODUCT_NAME column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS PRODUCT_NAME VARCHAR(100);

-- Step 6: Check if CATEGORY column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS CATEGORY VARCHAR(50);

-- Step 7: Check if QUANTITY column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS QUANTITY INTEGER;

-- Step 8: Check if UNIT_PRICE column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS UNIT_PRICE DECIMAL(10,2);

-- Step 9: Check if TOTAL_AMOUNT column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS TOTAL_AMOUNT DECIMAL(12,2);

-- Step 10: Check if CUSTOMER_ID column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS CUSTOMER_ID VARCHAR(20);

-- Step 11: Check if SALES_REP column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS SALES_REP VARCHAR(50);

-- Step 12: Check if REGION column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS REGION VARCHAR(30);

-- Step 13: Check if CREATED_AT column exists, if not add it
ALTER TABLE DQLABS_QA.STAGING.RETAIL_SALES 
ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();

-- Step 14: Verify the table structure
SELECT '=== TABLE ALTERED SUCCESSFULLY ===' as status;
DESCRIBE TABLE DQLABS_QA.STAGING.RETAIL_SALES;

-- Step 15: Show current data count
SELECT COUNT(*) as total_records FROM DQLABS_QA.STAGING.RETAIL_SALES;

-- Step 16: Show sample data with RECORD_ID
SELECT '=== SAMPLE DATA WITH RECORD_ID ===' as info;
SELECT RECORD_ID, "DATE", PRODUCT_NAME, CATEGORY, TOTAL_AMOUNT 
FROM DQLABS_QA.STAGING.RETAIL_SALES 
LIMIT 5; 