-- Create database and schema if they don't exist
CREATE DATABASE IF NOT EXISTS DQLABS_QA;
CREATE SCHEMA IF NOT EXISTS DQLABS_QA.DBT_MODELS;

-- Create staging table: stg_retail_sales
CREATE OR REPLACE TABLE DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES (
    RECORD_ID VARCHAR(50) NOT NULL,
    "DATE" DATE NOT NULL,
    STORE_ID VARCHAR(20) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    SALES_REP VARCHAR(50) NOT NULL,
    REGION VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create fact table: fct_electronics_sales
CREATE OR REPLACE TABLE DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES (
    RECORD_ID VARCHAR(50) NOT NULL,
    "DATE" DATE NOT NULL,
    STORE_ID VARCHAR(20) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    SALES_REP VARCHAR(50) NOT NULL,
    REGION VARCHAR(30) NOT NULL,
    CALCULATED_TOTAL DECIMAL(12,2) NOT NULL,
    PRICE_VALIDATION VARCHAR(20) NOT NULL,
    SALE_YEAR INTEGER NOT NULL,
    SALE_MONTH INTEGER NOT NULL,
    SALE_DAY INTEGER NOT NULL,
    SALE_QUARTER INTEGER NOT NULL,
    ORDER_SIZE VARCHAR(20) NOT NULL,
    ORDER_VALUE_CATEGORY VARCHAR(20) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DBT_RUN_ID VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create fact table: fct_macbook_air_sales
CREATE OR REPLACE TABLE DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES (
    RECORD_ID VARCHAR(50) NOT NULL,
    "DATE" DATE NOT NULL,
    STORE_ID VARCHAR(20) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    SALES_REP VARCHAR(50) NOT NULL,
    REGION VARCHAR(30) NOT NULL,
    PRODUCT_TYPE VARCHAR(20) NOT NULL,
    PRICE_TIER VARCHAR(20) NOT NULL,
    AVG_UNIT_PRICE DECIMAL(10,2) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(20) NOT NULL,
    REGION_GROUP VARCHAR(20) NOT NULL,
    SALE_YEAR INTEGER NOT NULL,
    SALE_MONTH INTEGER NOT NULL,
    SALE_DAY INTEGER NOT NULL,
    SALE_QUARTER INTEGER NOT NULL,
    SALE_DAY_OF_WEEK INTEGER NOT NULL,
    PURCHASE_TYPE VARCHAR(20) NOT NULL,
    ESTIMATED_PROFIT_MARGIN DECIMAL(12,2) NOT NULL,
    ESTIMATED_COMMISSION DECIMAL(12,2) NOT NULL,
    SALE_PERIOD VARCHAR(10) NOT NULL,
    SEASONAL_PERIOD VARCHAR(20) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DBT_RUN_ID VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create source table: retail_sales (in STAGING schema)
CREATE SCHEMA IF NOT EXISTS DQLABS_QA.STAGING;
CREATE OR REPLACE TABLE DQLABS_QA.STAGING.RETAIL_SALES (
    RECORD_ID VARCHAR(50) NOT NULL,
    "DATE" DATE NOT NULL,
    STORE_ID VARCHAR(20) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    SALES_REP VARCHAR(50) NOT NULL,
    REGION VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Grant permissions
GRANT USAGE ON SCHEMA DQLABS_QA.DBT_MODELS TO ROLE PUBLIC;
GRANT CREATE TABLE ON SCHEMA DQLABS_QA.DBT_MODELS TO ROLE PUBLIC;
GRANT CREATE VIEW ON SCHEMA DQLABS_QA.DBT_MODELS TO ROLE PUBLIC;
GRANT INSERT, SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DQLABS_QA.DBT_MODELS TO ROLE PUBLIC;

GRANT USAGE ON SCHEMA DQLABS_QA.STAGING TO ROLE PUBLIC;
GRANT CREATE TABLE ON SCHEMA DQLABS_QA.STAGING TO ROLE PUBLIC;
GRANT CREATE VIEW ON SCHEMA DQLABS_QA.STAGING TO ROLE PUBLIC;
GRANT INSERT, SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DQLABS_QA.STAGING TO ROLE PUBLIC; 