-- Fix zero records issue - Diagnose and push data
-- This script will check the source data and push it to target tables

-- Step 1: Check source data
SELECT '=== SOURCE DATA CHECK ===' as step;
SELECT COUNT(*) as source_records FROM DQLABS_QA.STAGING.RETAIL_SALES;

-- Step 2: Check what data exists in source
SELECT '=== SAMPLE SOURCE DATA ===' as step;
SELECT * FROM DQLABS_QA.STAGING.RETAIL_SALES LIMIT 5;

-- Step 3: Check for data quality issues
SELECT '=== DATA QUALITY CHECK ===' as step;
SELECT 
    'Total Records' as metric,
    COUNT(*) as value
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 
    'Records with NULL RECORD_ID',
    COUNT(CASE WHEN RECORD_ID IS NULL THEN 1 END)
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 
    'Records with NULL DATE',
    COUNT(CASE WHEN "DATE" IS NULL THEN 1 END)
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 
    'Records with NULL PRODUCT_NAME',
    COUNT(CASE WHEN PRODUCT_NAME IS NULL OR PRODUCT_NAME = '' THEN 1 END)
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 
    'Records with NULL CATEGORY',
    COUNT(CASE WHEN CATEGORY IS NULL THEN 1 END)
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 
    'Records with NULL QUANTITY',
    COUNT(CASE WHEN QUANTITY IS NULL THEN 1 END)
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 
    'Records with NULL UNIT_PRICE',
    COUNT(CASE WHEN UNIT_PRICE IS NULL THEN 1 END)
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 
    'Records with NULL TOTAL_AMOUNT',
    COUNT(CASE WHEN TOTAL_AMOUNT IS NULL THEN 1 END)
FROM DQLABS_QA.STAGING.RETAIL_SALES;

-- Step 4: Check categories in source data
SELECT '=== CATEGORIES IN SOURCE ===' as step;
SELECT 
    CATEGORY,
    COUNT(*) as record_count
FROM DQLABS_QA.STAGING.RETAIL_SALES
GROUP BY CATEGORY
ORDER BY record_count DESC;

-- Step 5: Check Electronics products specifically
SELECT '=== ELECTRONICS PRODUCTS ===' as step;
SELECT 
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
FROM DQLABS_QA.STAGING.RETAIL_SALES
WHERE UPPER(CATEGORY) LIKE '%ELECTRONIC%'
   OR LOWER(PRODUCT_NAME) LIKE '%iphone%'
   OR LOWER(PRODUCT_NAME) LIKE '%macbook%'
   OR LOWER(PRODUCT_NAME) LIKE '%samsung%'
   OR LOWER(PRODUCT_NAME) LIKE '%dell%'
ORDER BY TOTAL_AMOUNT DESC;

-- Step 6: Push data with minimal filtering (very permissive)
SELECT '=== PUSHING DATA WITH MINIMAL FILTERING ===' as step;

-- Clear existing data first
DELETE FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES;
DELETE FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES;
DELETE FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES;

-- Push to staging with very minimal filtering
INSERT INTO DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, 
    QUANTITY, UNIT_PRICE, TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION
)
SELECT 
    COALESCE(RECORD_ID, 'REC_' || ROW_NUMBER() OVER (ORDER BY "DATE")) as RECORD_ID,
    COALESCE("DATE", '2024-01-01') as "DATE",
    COALESCE(STORE_ID, 'STORE_UNKNOWN') as STORE_ID,
    COALESCE(PRODUCT_NAME, 'UNKNOWN_PRODUCT') as PRODUCT_NAME,
    COALESCE(CATEGORY, 'UNKNOWN_CATEGORY') as CATEGORY,
    COALESCE(QUANTITY, 1) as QUANTITY,
    COALESCE(UNIT_PRICE, 0.01) as UNIT_PRICE,
    COALESCE(TOTAL_AMOUNT, 0.01) as TOTAL_AMOUNT,
    COALESCE(CUSTOMER_ID, 'CUST_UNKNOWN') as CUSTOMER_ID,
    COALESCE(SALES_REP, 'SALES_UNKNOWN') as SALES_REP,
    COALESCE(REGION, 'UNKNOWN_REGION') as REGION
FROM DQLABS_QA.STAGING.RETAIL_SALES
WHERE RECORD_ID IS NOT NULL  -- Only filter out completely NULL records
   OR "DATE" IS NOT NULL;    -- Or records with no date

-- Step 7: Push to electronics sales (very permissive)
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, CALCULATED_TOTAL, 
    PRICE_VALIDATION, SALE_YEAR, SALE_MONTH, SALE_DAY, SALE_QUARTER, 
    ORDER_SIZE, ORDER_VALUE_CATEGORY, LOADED_AT, DBT_RUN_ID
)
SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    QUANTITY * UNIT_PRICE as CALCULATED_TOTAL,
    CASE 
        WHEN TOTAL_AMOUNT != (QUANTITY * UNIT_PRICE) THEN 'PRICE_MISMATCH'
        ELSE 'PRICE_MATCH'
    END as PRICE_VALIDATION,
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    CASE 
        WHEN QUANTITY >= 10 THEN 'BULK_ORDER'
        WHEN QUANTITY >= 5 THEN 'MEDIUM_ORDER'
        ELSE 'SMALL_ORDER'
    END as ORDER_SIZE,
    CASE 
        WHEN TOTAL_AMOUNT >= 1000 THEN 'HIGH_VALUE'
        WHEN TOTAL_AMOUNT >= 500 THEN 'MEDIUM_VALUE'
        ELSE 'LOW_VALUE'
    END as ORDER_VALUE_CATEGORY,
    CURRENT_TIMESTAMP() as LOADED_AT,
    'FIX_RUN_' || CURRENT_TIMESTAMP() as DBT_RUN_ID
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
WHERE UPPER(CATEGORY) LIKE '%ELECTRONIC%'
   OR LOWER(PRODUCT_NAME) LIKE '%iphone%'
   OR LOWER(PRODUCT_NAME) LIKE '%macbook%'
   OR LOWER(PRODUCT_NAME) LIKE '%samsung%'
   OR LOWER(PRODUCT_NAME) LIKE '%dell%'
   OR LOWER(PRODUCT_NAME) LIKE '%ipad%'
   OR LOWER(PRODUCT_NAME) LIKE '%apple%';

-- Step 8: Push to MacBook Air sales
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, PRODUCT_TYPE, PRICE_TIER, 
    AVG_UNIT_PRICE, CUSTOMER_SEGMENT, REGION_GROUP, SALE_YEAR, SALE_MONTH, 
    SALE_DAY, SALE_QUARTER, SALE_DAY_OF_WEEK, PURCHASE_TYPE, 
    ESTIMATED_PROFIT_MARGIN, ESTIMATED_COMMISSION, SALE_PERIOD, SEASONAL_PERIOD,
    LOADED_AT, DBT_RUN_ID
)
SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    CASE 
        WHEN LOWER(PRODUCT_NAME) LIKE '%macbook air%' THEN 'MACBOOK_AIR'
        WHEN LOWER(PRODUCT_NAME) LIKE '%macbook%' THEN 'OTHER_MACBOOK'
        ELSE 'NON_MACBOOK'
    END as PRODUCT_TYPE,
    CASE 
        WHEN UNIT_PRICE >= 1200 THEN 'PREMIUM_MODEL'
        WHEN UNIT_PRICE >= 900 THEN 'STANDARD_MODEL'
        ELSE 'BUDGET_MODEL'
    END as PRICE_TIER,
    TOTAL_AMOUNT / NULLIF(QUANTITY, 0) as AVG_UNIT_PRICE,
    CASE 
        WHEN TOTAL_AMOUNT >= 2000 THEN 'VIP_CUSTOMER'
        WHEN TOTAL_AMOUNT >= 1000 THEN 'PREMIUM_CUSTOMER'
        ELSE 'STANDARD_CUSTOMER'
    END as CUSTOMER_SEGMENT,
    CASE 
        WHEN UPPER(REGION) IN ('NORTH', 'NORTHEAST') THEN 'NORTH_REGION'
        WHEN UPPER(REGION) IN ('SOUTH', 'SOUTHEAST') THEN 'SOUTH_REGION'
        WHEN UPPER(REGION) IN ('WEST', 'SOUTHWEST') THEN 'WEST_REGION'
        WHEN UPPER(REGION) IN ('EAST') THEN 'EAST_REGION'
        ELSE 'OTHER_REGION'
    END as REGION_GROUP,
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    EXTRACT(DAYOFWEEK FROM "DATE") as SALE_DAY_OF_WEEK,
    CASE 
        WHEN QUANTITY >= 5 THEN 'BULK_PURCHASE'
        WHEN QUANTITY >= 2 THEN 'MULTIPLE_UNITS'
        ELSE 'SINGLE_UNIT'
    END as PURCHASE_TYPE,
    TOTAL_AMOUNT * 0.1 as ESTIMATED_PROFIT_MARGIN,
    TOTAL_AMOUNT * 0.05 as ESTIMATED_COMMISSION,
    CASE 
        WHEN EXTRACT(DAYOFWEEK FROM "DATE") IN (1, 7) THEN 'WEEKEND'
        ELSE 'WEEKDAY'
    END as SALE_PERIOD,
    CASE 
        WHEN EXTRACT(MONTH FROM "DATE") IN (11, 12) THEN 'HOLIDAY_SEASON'
        WHEN EXTRACT(MONTH FROM "DATE") IN (6, 7, 8) THEN 'SUMMER_SEASON'
        ELSE 'REGULAR_SEASON'
    END as SEASONAL_PERIOD,
    CURRENT_TIMESTAMP() as LOADED_AT,
    'FIX_RUN_' || CURRENT_TIMESTAMP() as DBT_RUN_ID
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
WHERE LOWER(PRODUCT_NAME) LIKE '%macbook air%'
   OR LOWER(PRODUCT_NAME) LIKE '%macbook%';

-- Step 9: Show final results
SELECT '=== FINAL RESULTS ===' as step;
SELECT 'STG_RETAIL_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
UNION ALL
SELECT 'FCT_ELECTRONICS_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES
UNION ALL
SELECT 'FCT_MACBOOK_AIR_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES;

-- Step 10: Show sample data
SELECT '=== SAMPLE STAGING DATA ===' as step;
SELECT * FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES LIMIT 3;

SELECT '=== SAMPLE ELECTRONICS DATA ===' as step;
SELECT RECORD_ID, PRODUCT_NAME, CATEGORY, TOTAL_AMOUNT, ORDER_SIZE 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES LIMIT 3;

SELECT '=== SAMPLE MACBOOK DATA ===' as step;
SELECT RECORD_ID, PRODUCT_NAME, PRICE_TIER, CUSTOMER_SEGMENT 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES LIMIT 3; 