-- Manually populate target tables using dbt model logic
-- This replicates what dbt run would do

-- Step 1: Populate staging table (stg_retail_sales)
-- This replicates the logic from models/stg_retail_sales.sql
INSERT INTO DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, 
    QUANTITY, UNIT_PRICE, TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION
)
WITH source_data AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION
  FROM DQLABS_QA.STAGING.RETAIL_SALES
  WHERE RECORD_ID IS NOT NULL
    AND "DATE" IS NOT NULL
    AND STORE_ID IS NOT NULL
    AND PRODUCT_NAME IS NOT NULL
    AND CATEGORY IS NOT NULL
    AND QUANTITY IS NOT NULL
    AND UNIT_PRICE IS NOT NULL
    AND TOTAL_AMOUNT IS NOT NULL
    AND CUSTOMER_ID IS NOT NULL
    AND SALES_REP IS NOT NULL
    AND REGION IS NOT NULL
),
deduplicated_data AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    ROW_NUMBER() OVER (
      PARTITION BY RECORD_ID 
      ORDER BY "DATE" DESC, TOTAL_AMOUNT DESC
    ) as rn
  FROM source_data
)
SELECT 
  RECORD_ID,
  "DATE",
  STORE_ID,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  CUSTOMER_ID,
  SALES_REP,
  REGION
FROM deduplicated_data
WHERE rn = 1;

-- Step 2: Populate electronics sales fact table
-- This replicates the logic from models/marts/fct_electronics_sales.sql
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, CALCULATED_TOTAL, 
    PRICE_VALIDATION, SALE_YEAR, SALE_MONTH, SALE_DAY, SALE_QUARTER, 
    ORDER_SIZE, ORDER_VALUE_CATEGORY, LOADED_AT, DBT_RUN_ID
)
WITH electronics_sales AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    -- Additional calculated fields
    QUANTITY * UNIT_PRICE as CALCULATED_TOTAL,
    CASE 
      WHEN TOTAL_AMOUNT != (QUANTITY * UNIT_PRICE) THEN 'PRICE_MISMATCH'
      ELSE 'PRICE_MATCH'
    END as PRICE_VALIDATION,
    -- Date dimensions
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    -- Business logic
    CASE 
      WHEN QUANTITY >= 10 THEN 'BULK_ORDER'
      WHEN QUANTITY >= 5 THEN 'MEDIUM_ORDER'
      ELSE 'SMALL_ORDER'
    END as ORDER_SIZE,
    CASE 
      WHEN TOTAL_AMOUNT >= 1000 THEN 'HIGH_VALUE'
      WHEN TOTAL_AMOUNT >= 500 THEN 'MEDIUM_VALUE'
      ELSE 'LOW_VALUE'
    END as ORDER_VALUE_CATEGORY
  FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
  WHERE CATEGORY = 'Electronics'
    AND PRODUCT_NAME IS NOT NULL
    AND QUANTITY > 0
    AND UNIT_PRICE > 0
    AND TOTAL_AMOUNT > 0
)
SELECT 
  RECORD_ID,
  "DATE",
  STORE_ID,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  CUSTOMER_ID,
  SALES_REP,
  REGION,
  CALCULATED_TOTAL,
  PRICE_VALIDATION,
  SALE_YEAR,
  SALE_MONTH,
  SALE_DAY,
  SALE_QUARTER,
  ORDER_SIZE,
  ORDER_VALUE_CATEGORY,
  CURRENT_TIMESTAMP() as LOADED_AT,
  'MANUAL_RUN_' || CURRENT_TIMESTAMP() as DBT_RUN_ID
FROM electronics_sales;

-- Step 3: Populate MacBook Air sales fact table
-- This replicates the logic from models/marts/fct_macbook_air_sales.sql
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, PRODUCT_TYPE, PRICE_TIER, 
    AVG_UNIT_PRICE, CUSTOMER_SEGMENT, REGION_GROUP, SALE_YEAR, SALE_MONTH, 
    SALE_DAY, SALE_QUARTER, SALE_DAY_OF_WEEK, PURCHASE_TYPE, 
    ESTIMATED_PROFIT_MARGIN, ESTIMATED_COMMISSION, SALE_PERIOD, SEASONAL_PERIOD,
    LOADED_AT, DBT_RUN_ID
)
WITH macbook_air_sales AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    -- MacBook Air specific analysis
    CASE 
      WHEN LOWER(PRODUCT_NAME) LIKE '%macbook air%' THEN 'MACBOOK_AIR'
      WHEN LOWER(PRODUCT_NAME) LIKE '%macbook%' THEN 'OTHER_MACBOOK'
      ELSE 'NON_MACBOOK'
    END as PRODUCT_TYPE,
    -- Price analysis
    CASE 
      WHEN UNIT_PRICE >= 1200 THEN 'PREMIUM_MODEL'
      WHEN UNIT_PRICE >= 900 THEN 'STANDARD_MODEL'
      ELSE 'BUDGET_MODEL'
    END as PRICE_TIER,
    -- Sales performance metrics
    TOTAL_AMOUNT / NULLIF(QUANTITY, 0) as AVG_UNIT_PRICE,
    -- Customer segmentation
    CASE 
      WHEN TOTAL_AMOUNT >= 2000 THEN 'VIP_CUSTOMER'
      WHEN TOTAL_AMOUNT >= 1000 THEN 'PREMIUM_CUSTOMER'
      ELSE 'STANDARD_CUSTOMER'
    END as CUSTOMER_SEGMENT,
    -- Regional analysis
    CASE 
      WHEN REGION IN ('North', 'Northeast') THEN 'NORTH_REGION'
      WHEN REGION IN ('South', 'Southeast') THEN 'SOUTH_REGION'
      WHEN REGION IN ('West', 'Southwest') THEN 'WEST_REGION'
      ELSE 'OTHER_REGION'
    END as REGION_GROUP,
    -- Time-based analysis
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    EXTRACT(DAYOFWEEK FROM "DATE") as SALE_DAY_OF_WEEK,
    -- Business intelligence
    CASE 
      WHEN QUANTITY >= 5 THEN 'BULK_PURCHASE'
      WHEN QUANTITY >= 2 THEN 'MULTIPLE_UNITS'
      ELSE 'SINGLE_UNIT'
    END as PURCHASE_TYPE,
    -- Revenue analysis
    TOTAL_AMOUNT * 0.1 as ESTIMATED_PROFIT_MARGIN,
    TOTAL_AMOUNT * 0.05 as ESTIMATED_COMMISSION
  FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
  WHERE LOWER(PRODUCT_NAME) LIKE '%macbook air%'
    AND CATEGORY = 'Electronics'
    AND QUANTITY > 0
    AND UNIT_PRICE > 0
    AND TOTAL_AMOUNT > 0
),
final_macbook_air AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    PRODUCT_TYPE,
    PRICE_TIER,
    AVG_UNIT_PRICE,
    CUSTOMER_SEGMENT,
    REGION_GROUP,
    SALE_YEAR,
    SALE_MONTH,
    SALE_DAY,
    SALE_QUARTER,
    SALE_DAY_OF_WEEK,
    PURCHASE_TYPE,
    ESTIMATED_PROFIT_MARGIN,
    ESTIMATED_COMMISSION,
    -- Additional calculated fields
    CASE 
      WHEN SALE_DAY_OF_WEEK IN (1, 7) THEN 'WEEKEND'
      ELSE 'WEEKDAY'
    END as SALE_PERIOD,
    CASE 
      WHEN SALE_MONTH IN (11, 12) THEN 'HOLIDAY_SEASON'
      WHEN SALE_MONTH IN (6, 7, 8) THEN 'SUMMER_SEASON'
      ELSE 'REGULAR_SEASON'
    END as SEASONAL_PERIOD
  FROM macbook_air_sales
)
SELECT 
  RECORD_ID,
  "DATE",
  STORE_ID,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  CUSTOMER_ID,
  SALES_REP,
  REGION,
  PRODUCT_TYPE,
  PRICE_TIER,
  AVG_UNIT_PRICE,
  CUSTOMER_SEGMENT,
  REGION_GROUP,
  SALE_YEAR,
  SALE_MONTH,
  SALE_DAY,
  SALE_QUARTER,
  SALE_DAY_OF_WEEK,
  PURCHASE_TYPE,
  ESTIMATED_PROFIT_MARGIN,
  ESTIMATED_COMMISSION,
  SALE_PERIOD,
  SEASONAL_PERIOD,
  CURRENT_TIMESTAMP() as LOADED_AT,
  'MANUAL_RUN_' || CURRENT_TIMESTAMP() as DBT_RUN_ID
FROM final_macbook_air;

-- Step 4: Verify the data was populated
SELECT 'Data Population Complete!' as status;

-- Show record counts for each table
SELECT 'Source Table (RETAIL_SALES)' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.STAGING.RETAIL_SALES
UNION ALL
SELECT 'Staging Table (STG_RETAIL_SALES)' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
UNION ALL
SELECT 'Electronics Sales (FCT_ELECTRONICS_SALES)' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES
UNION ALL
SELECT 'MacBook Air Sales (FCT_MACBOOK_AIR_SALES)' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES;

-- Show sample data from each table
SELECT 'Sample from STG_RETAIL_SALES:' as info;
SELECT * FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES LIMIT 5;

SELECT 'Sample from FCT_ELECTRONICS_SALES:' as info;
SELECT RECORD_ID, PRODUCT_NAME, TOTAL_AMOUNT, ORDER_SIZE, ORDER_VALUE_CATEGORY 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES LIMIT 5;

SELECT 'Sample from FCT_MACBOOK_AIR_SALES:' as info;
SELECT RECORD_ID, PRODUCT_NAME, PRICE_TIER, CUSTOMER_SEGMENT, REGION_GROUP 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES LIMIT 5; 