-- Push data to target tables based on custom conditions
-- You can modify the conditions below to control what data gets pushed

-- Step 1: Clear existing data from target tables (optional)
-- Uncomment the lines below if you want to start fresh
-- DELETE FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES;
-- DELETE FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES;
-- DELETE FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES;

-- Step 2: Push data to staging table with custom conditions
INSERT INTO DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, 
    QUANTITY, UNIT_PRICE, TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION
)
WITH source_data AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION
  FROM DQLABS_QA.STAGING.RETAIL_SALES
  WHERE 
    -- CUSTOM CONDITIONS - MODIFY THESE AS NEEDED
    RECORD_ID IS NOT NULL
    AND "DATE" IS NOT NULL
    AND STORE_ID IS NOT NULL
    AND PRODUCT_NAME IS NOT NULL AND PRODUCT_NAME != ''
    AND CATEGORY IS NOT NULL
    AND QUANTITY IS NOT NULL AND QUANTITY > 0  -- Only positive quantities
    AND UNIT_PRICE IS NOT NULL AND UNIT_PRICE > 0  -- Only positive prices
    AND TOTAL_AMOUNT IS NOT NULL AND TOTAL_AMOUNT > 0  -- Only positive amounts
    -- Add your custom conditions here:
    -- AND CATEGORY = 'Electronics'  -- Uncomment to filter by category
    -- AND TOTAL_AMOUNT >= 1000      -- Uncomment to filter by amount
    -- AND REGION = 'North'          -- Uncomment to filter by region
    -- AND "DATE" >= '2024-01-01'    -- Uncomment to filter by date
),
deduplicated_data AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    ROW_NUMBER() OVER (
      PARTITION BY RECORD_ID 
      ORDER BY "DATE" DESC, TOTAL_AMOUNT DESC
    ) as rn
  FROM source_data
)
SELECT 
  RECORD_ID,
  "DATE",
  STORE_ID,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  COALESCE(CUSTOMER_ID, 'UNKNOWN') as CUSTOMER_ID,
  SALES_REP,
  REGION
FROM deduplicated_data
WHERE rn = 1;

-- Step 3: Push data to electronics sales fact table with conditions
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, CALCULATED_TOTAL, 
    PRICE_VALIDATION, SALE_YEAR, SALE_MONTH, SALE_DAY, SALE_QUARTER, 
    ORDER_SIZE, ORDER_VALUE_CATEGORY, LOADED_AT, DBT_RUN_ID
)
WITH electronics_sales AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    QUANTITY * UNIT_PRICE as CALCULATED_TOTAL,
    CASE 
      WHEN TOTAL_AMOUNT != (QUANTITY * UNIT_PRICE) THEN 'PRICE_MISMATCH'
      ELSE 'PRICE_MATCH'
    END as PRICE_VALIDATION,
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    CASE 
      WHEN QUANTITY >= 10 THEN 'BULK_ORDER'
      WHEN QUANTITY >= 5 THEN 'MEDIUM_ORDER'
      ELSE 'SMALL_ORDER'
    END as ORDER_SIZE,
    CASE 
      WHEN TOTAL_AMOUNT >= 1000 THEN 'HIGH_VALUE'
      WHEN TOTAL_AMOUNT >= 500 THEN 'MEDIUM_VALUE'
      ELSE 'LOW_VALUE'
    END as ORDER_VALUE_CATEGORY
  FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
  WHERE 
    -- CUSTOM CONDITIONS FOR ELECTRONICS - MODIFY THESE AS NEEDED
    UPPER(CATEGORY) = 'ELECTRONICS'
    AND PRODUCT_NAME IS NOT NULL
    AND QUANTITY > 0
    AND UNIT_PRICE > 0
    AND TOTAL_AMOUNT > 0
    -- Add your custom conditions here:
    -- AND TOTAL_AMOUNT >= 500        -- Uncomment to filter by minimum amount
    -- AND PRODUCT_NAME LIKE '%iPhone%'  -- Uncomment to filter by product
    -- AND REGION IN ('North', 'South')  -- Uncomment to filter by regions
    -- AND "DATE" >= '2024-01-15'     -- Uncomment to filter by date
)
SELECT 
  RECORD_ID,
  "DATE",
  STORE_ID,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  CUSTOMER_ID,
  SALES_REP,
  REGION,
  CALCULATED_TOTAL,
  PRICE_VALIDATION,
  SALE_YEAR,
  SALE_MONTH,
  SALE_DAY,
  SALE_QUARTER,
  ORDER_SIZE,
  ORDER_VALUE_CATEGORY,
  CURRENT_TIMESTAMP() as LOADED_AT,
  'CONDITIONAL_RUN_' || CURRENT_TIMESTAMP() as DBT_RUN_ID
FROM electronics_sales;

-- Step 4: Push data to MacBook Air sales fact table with conditions
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, PRODUCT_TYPE, PRICE_TIER, 
    AVG_UNIT_PRICE, CUSTOMER_SEGMENT, REGION_GROUP, SALE_YEAR, SALE_MONTH, 
    SALE_DAY, SALE_QUARTER, SALE_DAY_OF_WEEK, PURCHASE_TYPE, 
    ESTIMATED_PROFIT_MARGIN, ESTIMATED_COMMISSION, SALE_PERIOD, SEASONAL_PERIOD,
    LOADED_AT, DBT_RUN_ID
)
WITH macbook_air_sales AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    CASE 
      WHEN LOWER(PRODUCT_NAME) LIKE '%macbook air%' THEN 'MACBOOK_AIR'
      WHEN LOWER(PRODUCT_NAME) LIKE '%macbook%' THEN 'OTHER_MACBOOK'
      ELSE 'NON_MACBOOK'
    END as PRODUCT_TYPE,
    CASE 
      WHEN UNIT_PRICE >= 1200 THEN 'PREMIUM_MODEL'
      WHEN UNIT_PRICE >= 900 THEN 'STANDARD_MODEL'
      ELSE 'BUDGET_MODEL'
    END as PRICE_TIER,
    TOTAL_AMOUNT / NULLIF(QUANTITY, 0) as AVG_UNIT_PRICE,
    CASE 
      WHEN TOTAL_AMOUNT >= 2000 THEN 'VIP_CUSTOMER'
      WHEN TOTAL_AMOUNT >= 1000 THEN 'PREMIUM_CUSTOMER'
      ELSE 'STANDARD_CUSTOMER'
    END as CUSTOMER_SEGMENT,
    CASE 
      WHEN UPPER(REGION) IN ('NORTH', 'NORTHEAST') THEN 'NORTH_REGION'
      WHEN UPPER(REGION) IN ('SOUTH', 'SOUTHEAST') THEN 'SOUTH_REGION'
      WHEN UPPER(REGION) IN ('WEST', 'SOUTHWEST') THEN 'WEST_REGION'
      WHEN UPPER(REGION) IN ('EAST') THEN 'EAST_REGION'
      ELSE 'OTHER_REGION'
    END as REGION_GROUP,
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    EXTRACT(DAYOFWEEK FROM "DATE") as SALE_DAY_OF_WEEK,
    CASE 
      WHEN QUANTITY >= 5 THEN 'BULK_PURCHASE'
      WHEN QUANTITY >= 2 THEN 'MULTIPLE_UNITS'
      ELSE 'SINGLE_UNIT'
    END as PURCHASE_TYPE,
    TOTAL_AMOUNT * 0.1 as ESTIMATED_PROFIT_MARGIN,
    TOTAL_AMOUNT * 0.05 as ESTIMATED_COMMISSION
  FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
  WHERE 
    -- CUSTOM CONDITIONS FOR MACBOOK AIR - MODIFY THESE AS NEEDED
    LOWER(PRODUCT_NAME) LIKE '%macbook air%'
    AND UPPER(CATEGORY) = 'ELECTRONICS'
    AND QUANTITY > 0
    AND UNIT_PRICE > 0
    AND TOTAL_AMOUNT > 0
    -- Add your custom conditions here:
    -- AND UNIT_PRICE >= 1000        -- Uncomment to filter by minimum price
    -- AND TOTAL_AMOUNT >= 1000      -- Uncomment to filter by minimum amount
    -- AND REGION = 'North'          -- Uncomment to filter by region
    -- AND "DATE" >= '2024-01-01'    -- Uncomment to filter by date
),
final_macbook_air AS (
  SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    PRODUCT_TYPE,
    PRICE_TIER,
    AVG_UNIT_PRICE,
    CUSTOMER_SEGMENT,
    REGION_GROUP,
    SALE_YEAR,
    SALE_MONTH,
    SALE_DAY,
    SALE_QUARTER,
    SALE_DAY_OF_WEEK,
    PURCHASE_TYPE,
    ESTIMATED_PROFIT_MARGIN,
    ESTIMATED_COMMISSION,
    CASE 
      WHEN SALE_DAY_OF_WEEK IN (1, 7) THEN 'WEEKEND'
      ELSE 'WEEKDAY'
    END as SALE_PERIOD,
    CASE 
      WHEN SALE_MONTH IN (11, 12) THEN 'HOLIDAY_SEASON'
      WHEN SALE_MONTH IN (6, 7, 8) THEN 'SUMMER_SEASON'
      ELSE 'REGULAR_SEASON'
    END as SEASONAL_PERIOD
  FROM macbook_air_sales
)
SELECT 
  RECORD_ID,
  "DATE",
  STORE_ID,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  CUSTOMER_ID,
  SALES_REP,
  REGION,
  PRODUCT_TYPE,
  PRICE_TIER,
  AVG_UNIT_PRICE,
  CUSTOMER_SEGMENT,
  REGION_GROUP,
  SALE_YEAR,
  SALE_MONTH,
  SALE_DAY,
  SALE_QUARTER,
  SALE_DAY_OF_WEEK,
  PURCHASE_TYPE,
  ESTIMATED_PROFIT_MARGIN,
  ESTIMATED_COMMISSION,
  SALE_PERIOD,
  SEASONAL_PERIOD,
  CURRENT_TIMESTAMP() as LOADED_AT,
  'CONDITIONAL_RUN_' || CURRENT_TIMESTAMP() as DBT_RUN_ID
FROM final_macbook_air;

-- Step 5: Show results
SELECT 'Data Push Complete with Custom Conditions!' as status;

-- Show record counts
SELECT 'Final Record Counts' as info;
SELECT 'STG_RETAIL_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
UNION ALL
SELECT 'FCT_ELECTRONICS_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES
UNION ALL
SELECT 'FCT_MACBOOK_AIR_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES;

-- Show sample data
SELECT 'Sample Electronics Sales:' as info;
SELECT RECORD_ID, PRODUCT_NAME, CATEGORY, TOTAL_AMOUNT, ORDER_SIZE 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES LIMIT 5;

SELECT 'Sample MacBook Air Sales:' as info;
SELECT RECORD_ID, PRODUCT_NAME, PRICE_TIER, CUSTOMER_SEGMENT, REGION_GROUP 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES LIMIT 5; 