-- Show sample data from each table to verify content

-- 1. Sample from source table
SELECT '=== SAMPLE SOURCE DATA ===' as table_info;
SELECT RECORD_ID, "DATE", PRODUCT_NAME, CATEGORY, TOTAL_AMOUNT 
FROM DQLABS_QA.STAGING.RETAIL_SALES 
LIMIT 5;

-- 2. Sample from staging table
SELECT '=== SAMPLE STAGING DATA ===' as table_info;
SELECT RECORD_ID, "DATE", PRODUCT_NAME, CATEGORY, TOTAL_AMOUNT 
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES 
LIMIT 5;

-- 3. Sample from electronics sales
SELECT '=== SAMPLE ELECTRONICS DATA ===' as table_info;
SELECT RECORD_ID, PRODUCT_NAME, CATEGORY, TOTAL_AMOUNT, ORDER_SIZE, ORDER_VALUE_CATEGORY 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES 
LIMIT 5;

-- 4. Sample from MacBook Air sales
SELECT '=== SAMPLE MACBOOK AIR DATA ===' as table_info;
SELECT RECORD_ID, PRODUCT_NAME, PRICE_TIER, CUSTOMER_SEGMENT, REGION_GROUP 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES 
LIMIT 5; 