-- SECTION 5: Populate MacBook Air sales (run this fifth)
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, PRODUCT_TYPE, PRICE_TIER, 
    AVG_UNIT_PRICE, CUSTOMER_SEGMENT, REGION_GROUP, SALE_YEAR, SALE_MONTH, 
    SALE_DAY, SALE_QUARTER, SALE_DAY_OF_WEEK, PURCHASE_TYPE, 
    ESTIMATED_PROFIT_MARGIN, ESTIMATED_COMMISSION, SALE_PERIOD, SEASONAL_PERIOD,
    LOADED_AT, DBT_RUN_ID
)
SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    CASE 
        WHEN LOWER(PRODUCT_NAME) LIKE '%macbook air%' THEN 'MACBOOK_AIR'
        WHEN LOWER(PRODUCT_NAME) LIKE '%macbook%' THEN 'OTHER_MACBOOK'
        ELSE 'NON_MACBOOK'
    END as PRODUCT_TYPE,
    CASE 
        WHEN UNIT_PRICE >= 1200 THEN 'PREMIUM_MODEL'
        WHEN UNIT_PRICE >= 900 THEN 'STANDARD_MODEL'
        ELSE 'BUDGET_MODEL'
    END as PRICE_TIER,
    TOTAL_AMOUNT / NULLIF(QUANTITY, 0) as AVG_UNIT_PRICE,
    CASE 
        WHEN TOTAL_AMOUNT >= 2000 THEN 'VIP_CUSTOMER'
        WHEN TOTAL_AMOUNT >= 1000 THEN 'PREMIUM_CUSTOMER'
        ELSE 'STANDARD_CUSTOMER'
    END as CUSTOMER_SEGMENT,
    CASE 
        WHEN UPPER(REGION) IN ('NORTH', 'NORTHEAST') THEN 'NORTH_REGION'
        WHEN UPPER(REGION) IN ('SOUTH', 'SOUTHEAST') THEN 'SOUTH_REGION'
        WHEN UPPER(REGION) IN ('WEST', 'SOUTHWEST') THEN 'WEST_REGION'
        WHEN UPPER(REGION) IN ('EAST') THEN 'EAST_REGION'
        ELSE 'OTHER_REGION'
    END as REGION_GROUP,
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    EXTRACT(DAYOFWEEK FROM "DATE") as SALE_DAY_OF_WEEK,
    CASE 
        WHEN QUANTITY >= 5 THEN 'BULK_PURCHASE'
        WHEN QUANTITY >= 2 THEN 'MULTIPLE_UNITS'
        ELSE 'SINGLE_UNIT'
    END as PURCHASE_TYPE,
    TOTAL_AMOUNT * 0.1 as ESTIMATED_PROFIT_MARGIN,
    TOTAL_AMOUNT * 0.05 as ESTIMATED_COMMISSION,
    CASE 
        WHEN EXTRACT(DAYOFWEEK FROM "DATE") IN (1, 7) THEN 'WEEKEND'
        ELSE 'WEEKDAY'
    END as SALE_PERIOD,
    CASE 
        WHEN EXTRACT(MONTH FROM "DATE") IN (11, 12) THEN 'HOLIDAY_SEASON'
        WHEN EXTRACT(MONTH FROM "DATE") IN (6, 7, 8) THEN 'SUMMER_SEASON'
        ELSE 'REGULAR_SEASON'
    END as SEASONAL_PERIOD,
    CURRENT_TIMESTAMP() as LOADED_AT,
    'SIMPLE_FIX_RUN' as DBT_RUN_ID
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
WHERE LOWER(PRODUCT_NAME) LIKE '%macbook air%'
   OR LOWER(PRODUCT_NAME) LIKE '%macbook%'; 