-- SECTION 3: Populate staging table (run this third)
INSERT INTO DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, 
    QUANTITY, UNIT_PRICE, TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION
)
SELECT 
    COALESCE(RECORD_ID, 'REC_' || ROW_NUMBER() OVER (ORDER BY "DATE")) as RECORD_ID,
    COALESCE("DATE", '2024-01-01') as "DATE",
    COALESCE(STORE_ID, 'STORE_UNKNOWN') as STORE_ID,
    COALESCE(PRODUCT_NAME, 'UNKNOWN_PRODUCT') as PRODUCT_NAME,
    COALESCE(CATEGORY, 'UNKNOWN_CATEGORY') as CATEGORY,
    COALESCE(QUANTITY, 1) as QUANTITY,
    COALESCE(UNIT_PRICE, 0.01) as UNIT_PRICE,
    COALESCE(TOTAL_AMOUNT, 0.01) as TOTAL_AMOUNT,
    COALESCE(CUSTOMER_ID, 'CUST_UNKNOWN') as CUSTOMER_ID,
    COALESCE(SALES_REP, 'SALES_UNKNOWN') as SALES_REP,
    COALESCE(REGION, 'UNKNOWN_REGION') as REGION
FROM DQLABS_QA.STAGING.RETAIL_SALES
WHERE RECORD_ID IS NOT NULL OR "DATE" IS NOT NULL; 