-- SECTION 4: Populate electronics sales (run this fourth)
INSERT INTO DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES (
    RECORD_ID, "DATE", STORE_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, 
    TOTAL_AMOUNT, CUSTOMER_ID, SALES_REP, REGION, CALCULATED_TOTAL, 
    PRICE_VALIDATION, SALE_YEAR, SALE_MONTH, SALE_DAY, SALE_QUARTER, 
    ORDER_SIZE, ORDER_VALUE_CATEGORY, LOADED_AT, DBT_RUN_ID
)
SELECT 
    RECORD_ID,
    "DATE",
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    QUANTITY * UNIT_PRICE as CALCULATED_TOTAL,
    CASE 
        WHEN TOTAL_AMOUNT != (QUANTITY * UNIT_PRICE) THEN 'PRICE_MISMATCH'
        ELSE 'PRICE_MATCH'
    END as PRICE_VALIDATION,
    EXTRACT(YEAR FROM "DATE") as SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") as SALE_MONTH,
    EXTRACT(DAY FROM "DATE") as SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") as SALE_QUARTER,
    CASE 
        WHEN QUANTITY >= 10 THEN 'BULK_ORDER'
        WHEN QUANTITY >= 5 THEN 'MEDIUM_ORDER'
        ELSE 'SMALL_ORDER'
    END as ORDER_SIZE,
    CASE 
        WHEN TOTAL_AMOUNT >= 1000 THEN 'HIGH_VALUE'
        WHEN TOTAL_AMOUNT >= 500 THEN 'MEDIUM_VALUE'
        ELSE 'LOW_VALUE'
    END as ORDER_VALUE_CATEGORY,
    CURRENT_TIMESTAMP() as LOADED_AT,
    'SIMPLE_FIX_RUN' as DBT_RUN_ID
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
WHERE UPPER(CATEGORY) LIKE '%ELECTRONIC%'
   OR LOWER(PRODUCT_NAME) LIKE '%iphone%'
   OR LOWER(PRODUCT_NAME) LIKE '%macbook%'
   OR LOWER(PRODUCT_NAME) LIKE '%samsung%'
   OR LOWER(PRODUCT_NAME) LIKE '%dell%'
   OR LOWER(PRODUCT_NAME) LIKE '%ipad%'
   OR LOWER(PRODUCT_NAME) LIKE '%apple%'; 