-- SECTION 2: Clear existing data (run this second)
DELETE FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES;
DELETE FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES;
DELETE FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES; 