-- SECTION 6: Check results (run this last)
SELECT 'STG_RETAIL_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.STG_RETAIL_SALES
UNION ALL
SELECT 'FCT_ELECTRONICS_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_ELECTRONICS_SALES
UNION ALL
SELECT 'FCT_MACBOOK_AIR_SALES' as table_name, COUNT(*) as record_count 
FROM DQLABS_QA.DBT_MODELS.FCT_MACBOOK_AIR_SALES; 